language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - ~/.m2

install: true
script: mvn -B --global-toolchains travis-maven-toolchain.xml clean install -DskipTests | grep -E '\[WARNING\]|\[ERROR\]' &&
        mvn -B --global-toolchains travis-maven-toolchain.xml -pl :org.eclipse.birt.core.tests integration-test | grep -E '\[WARNING\]|\[ERROR\]'
before_cache:
  - rm -r ~/.m2/repository/org/eclipse/birt
  - rm -r ~/.m2/repository/.cache/tycho
